# OHI Configuration File
# For PM2, there is nothing to configure
# Copy file to: /etc/newrelic-infra/integrations.d/
integration_name: com.newrelic.pm2ohi
instances:
  - name: pm2ohi
    command: all
    arguments:
    labels:
      environment: production
      role: container
